// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitMission(a string) *Mission {
	player := NewPlayer(a)
	monster := NewMonster(a)
	mission := NewMission(player, monster)
	return mission
}

func InitMission3(a string) *Mission {
	player := NewPlayer(a)
	monster := NewMonster(a)
	mission := NewMission(player, monster)
	return mission
}
